class paginaFavoritos{
    botonCatalogos(){
        cy.get('div[id="Catálogos"]').click();
    }
    botonMisFavoritos(){
        cy.get('div[id="Mis productos favoritos"]').click();
    }
    botonDermazone(){
        cy.get('div[id="btn-dermazone"]').click();
    }
    botonReve(){
        cy.get('div[id="btn-reve"]').click();
    }
    botonBioequal(){
        cy.get('div[id="btn-bioequal"]').click();
    }
    botonBioelite(){
        cy.get('div[id="btn-bioelite"]').click();
    }
    botonGuardar(){
        cy.get('button[name="btn-save"]').click();
    }
    botonAceptar(){
        cy.get('button[name="btn-accept"]').click();
        cy.wait(3000);
    }
    botonFavorito(producto){
        cy.get(`div[id="btn-${producto.toLowerCase()}-favorite"]`).click();
    }
    seleccionarPresentacion(presentacion){
        cy.get(`app-catalog-combobox[id="presentatation"]`).click().click();
        cy.wait(1000);
        cy.get("span").contains(presentacion).click();
    }
    seleccionarEtiqueta(producto,etiqueta){
        cy.get(`mat-select[id="btn-label${producto.toLowerCase()}"]`).click();
        cy.get(`mat-option[id="option-label-${etiqueta.toLowerCase()}"]`).click();
    }
    seleccionarEnvase(producto,envase){
        cy.get(`div[id="btn-container${producto.toLowerCase()}"]`).click();
        cy.get(`mat-radio-button[id="check-${envase.toLowerCase()}"]`).click();
    }
    buscarProducto(producto){
        cy.wait(2000);
        cy.get(`app-catalog-input-text[id="code"]`).click().type(producto).type('{enter}');
    }
    buscarProductoPrincipioActivo(producto){
        cy.wait(1000);
        cy.get(`app-catalog-combobox[id="active-principle"]`).type(producto);
        cy.get(`mat-option`).click();
    }
    botonLimpiar(){
        cy.get('button[name="btn-clear"]').click();
    }
    botonInicio(){
        cy.get('div[id="btn-home"]').click();
    }
    botonEliminarFavorito(producto){
        cy.get(`div[id="btn-${producto.toLowerCase()}-favorite"]`).first().click();
    }
}

export default paginaFavoritos;